@startjson tds
{ "types" : [ { "class" : "Type",
"token" : "5",
"id" : "pointer" },
{ "class" : "Type",
"token" : "3",
"id" : "void" },
{ "class" : "Type",
"token" : "2",
"id" : "string" },
{ "class" : "Type",
"token" : "1",
"id" : "int" } ],
"variables" : [ { "class" : "Value",
"token" : "7",
"id" : "print",
"type" : { "class" : "FunctionType",
"token" : "6",
"inType1" : "string",
"outType" : "void" } } ],
"tdsChild" : { "types" : [  ],
"variables" : [ { "class" : "Value",
"token" : "13",
"id" : "a",
"type" : "int" },
{ "class" : "Value",
"token" : "12",
"id" : "s",
"type" : { "class" : "FunctionType",
"token" : "8",
"inType1" : "int",
"inType2" : "int",
"outType" : "int" } } ] } }
@endjson